### ISSUE TITLE
Add an unsnapped kiai check

### ISSUE THREAD

**Issue by hongaaronc** [Hiviexd/MVTaikoChecks#7]
Aimod already has it, and I think it's just kind of annoying having to check both Aimod and MV. So it'd be nice to put it in MV as a central place with everything.

Also not sure if there's other checks which are Aimod only but if so, would be good to copy those over as well.

**Comment by Hiviexd** [comment]
mv has an unsnapped kiai check by default, it has low visibility tho because it's minor

![image](https://github.com/Hiviexd/MVTaikoChecks/assets/62819481/cdb418da-b565-46ee-b2de-3d45bd086f85)

however i think that the taiko limit should be raised to `1ms or more = warning` to match aimod and our expectations

**Comment by Hiviexd** [comment]
will close this for now considering that it's currently out of scope for the plugin
